repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--config, pyproject.toml]
        files: ^cpt_categorizer/
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
        files: ^cpt_categorizer/
